### ISSUE TITLE
Missing "program" path when renaming asconfig.json

### ISSUE THREAD

**Issue by Zageron** [BowlerHatLLC/vscode-swf-debug#10]
When I hit F5, I get the following error pop-up:
Missing "program" path for SWF debug configuration. Must be a .swf file or an Adobe AIR application descriptor.

I've resolved the issue, but I believe it is a bug.

I have three asconfigs:
asconfig.develop.json
asconfig.release.json (bundle)
asconfig.steam.json (native)

If I rename asconfig.develop.json to asconfig.json F5 functions again.

**Comment by joshtynjala** [comment]
This is the expected behavior. It is not a bug. _asconfig.json_ is your main project file that must exist for not just debugging, but also full code intelligence. Other asconfig.*.json files can be used to provide extra build tasks, but they do not affect code intelligence or debugging.
