### ISSUE TITLE
Terminating Worker thread crashes the debugger/app

### ISSUE THREAD

**Issue by kennylerma** [BowlerHatLLC/vscode-swf-debug#18]
I assume this has something to do with how you're keeping track of the running threads in vscode and when one is terminated the whole app exits.  I discovered this by testing my app with FlashDevelop where I'm terminating and restarting a background worker and it works as expected.

Kenny

**Comment by joshtynjala** [comment]
If you can create a simple project that demonstrates the issue, that would help a lot. I can tell you that during my testing, I didn't encounter anything like this. Workers could be terminated, and the list of threads updated without a crash.

**Comment by kennylerma** [comment]
I'll work up a project this weekend.

**Comment by Adolio** [comment]
FYI, here is a thread on this topic on the Adobe-Runtime-Support project: https://github.com/airsdk/Adobe-Runtime-Support/issues/2523. 

I have provided a sample project to reproduce the issue in this comment (no answer yet): https://github.com/airsdk/Adobe-Runtime-Support/issues/2523#issuecomment-2268863447
