### ISSUE TITLE
Launch on Android device fails

### ISSUE THREAD

**Issue by aliwithay** [BowlerHatLLC/vscode-swf-debug#28]
I am trying to import our company Air Mobile project from Flash Builder over to vscode, and I have been able to use the import tool to set it up, compile, and debug on the simulator for both iOS and Android, however, trying to debug on device for Android fails to install with status code 14, if the app is already installed on the device. I can uninstall the app and the install works fine. I read on some of the other issues that air tool should uninstall on each launch, but that does not seem to be working for me. Even when I do uninstall the app and try to debug, the task fails on Launch with the same error code. I have tried this with multiple devices and it fails on all of them.

AIR SDK version: 33.1.1.533
Java version: 1.8.0_301 x64

**Comment by aliwithay** [comment]
I figured out the issue. It seems like I was using the wrong App ID from what was on the certificate and this was causing the issue. It also seems to have fixed the uninstall issue.

**Comment by joshtynjala** [comment]
Great! Thanks for the update.
