### ISSUE TITLE
Invalid variable attributes

### ISSUE THREAD

**Issue by ba0f3** [BowlerHatLLC/vscode-swf-debug#3]
When I debug flash application with flashplayerdebugger, it shows some variables, properties as "Invalid variable attributes". I use Debugger for SWF 1.0.1, on both Linux (debugger run on same computer), and Mac (mac remote to Linux).

![Screen Shot 2019-12-25 at 23 10 45](https://user-images.githubusercontent.com/106477/71448343-68b78e80-276d-11ea-8896-9ddfdcc14435.png)

**Comment by joshtynjala** [comment]
@ba0f3 Can you try the vscode-swf-debug v1.0.2 update, and let me know you still encounter this issue?

When I tried on my Xubuntu Linux box, the variables view seemed to be working correctly when I paused at a breakpoint, so I am currently unable to reproduce the issue. If it's still happening, we're going to need to figure out some more clues that might help.

**Comment by ba0f3** [comment]
Thank you, I will try new version and get back to you soon

**Comment by ba0f3** [comment]
I am sorry, I forgot to tell you that I were using VSCode Insiders. It works fine for VSCode 1.41, but problem  came from VSCode Insiders.
