### ISSUE TITLE
Cannot inspect local constants at runtime

### ISSUE THREAD

**Issue by mat100payette** [BowlerHatLLC/vscode-swf-debug#37]
We use local `const` declarations to clearly show intent of what locals can and cannot be overriden in scope.
However, `const` locals do not show up in the debug locals, and cannot be evaluated at runtime when paused on a breakpoint in the same scope.

This is problematic since we would be stuck using `var` mostly everywhere.

**Comment by joshtynjala** [comment]
Unfortunately, I've never found a way to query the debugger for local constants.

**Comment by mat100payette** [comment]
> Unfortunately, I've never found a way to query the debugger for local constants.

I see. Do you have any idea of why that'd be impossible to get ? Also, describing any failed attempt could help maybe. I'll give it a look when I get some time.

**Comment by joshtynjala** [comment]
Locals are accessed here when displaying variables:

https://github.com/BowlerHatLLC/vscode-swf-debug/blob/6fc72a81ce34b5c576fe2fdf4d8cd451a995944b/swf-debug-adapter/src/main/java/com/as3mxml/vscode/SWFDebugSession.java#L1743

And here when evaluating expressions:

https://github.com/BowlerHatLLC/vscode-swf-debug/blob/684e9c0e5ee4e60610039d4a839bb944d5b38b22/swf-debug-adapter/src/main/java/com/as3mxml/vscode/SWFExpressionContext.java#L66

**Comment by mat100payette** [comment]
@joshtynjala I've built the code in my fork. Would you mind helping me figure out how to run/test/debug the extension? My email is matpayette@hotmail.com (just so we dont derail this issue).

**Comment by joshtynjala** [comment]
You should be able to run the "Launch Extension" launch configuration when you open vscode-swf-debug as a workspace in Visual Studio Code. This will launch the Extension Host with your locally built version of the extension.

To debug the Java, you'll also need to run the "Debug SWF Debug Adapter (Attach)" launch configuration at the same time (I don't recall which launch configuration needs to be started first, though). Before you do that, uncomment this line:

https://github.com/BowlerHatLLC/vscode-swf-debug/blob/ff65b95/vscode-extension/src/main/ts/utils/SWFDebugAdapterDescriptorFactory.ts#L46

Or at least that's how it should work. I haven't tried running the Java code in the Java debugger for a very long time, so I don't know if it still works or not.

**Comment by mat100payette** [comment]
Oof. I'm not having much success it seems. When I launch from workspace, I get this:

> Executing task in folder vscode-swf-debug: D:\ApacheMaven\apache-maven-3.8.4\bin\mvn package -Dskip-vsce=true -DskipTests <
>
> The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 193).

And when I try to run the debug adapter, I get this (in a popup error):

> Failed to attach remote debuggee VM. Reason: java.net.ConnectException: Connection refused: connect

Hmm...

**Comment by joshtynjala** [comment]
> The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 193).

Some kind of issue with Java or Maven, I suppose. I won't be able to provide much in the way of suggestions, I'm guessing.

> And when I try to run the debug adapter, I get this (in a popup error):

This is expected, since you can't launch the extension. The extension runs the debug adapter. The "Debug SWF Debug Adapter (Attach)" launch configuration simply waits for when the debug adapter is started by the extension.

**Comment by mat100payette** [comment]
![image](https://user-images.githubusercontent.com/20545324/148275541-f6ac8f40-e1bf-4a1d-8cac-2fa6233156a0.png)

Here's the errors/warnings I have in console. All I've done so far is install the dependencies listed in the ReadMe in order (JDK 17, Maven 3.8.4 and Node 16.13.1). Then I ran `mvn clean package` in root folder to build. After that, launching the things gave be the errors I mentioned in prior post. Rebooting my computer didn't fix it. I'm running on Windows 10.

**Comment by joshtynjala** [comment]
All of the warnings there look normal, but the 'vscode' type declaration error is not normal. That should be resolved when running the man package command. It may be that you simply need to restart VSCode to clear it after a successful compile from Maven. Note that you don't need to manually build with Maven. The launch will do it automatically.

> D:\ApacheMaven\apache-maven-3.8.4\bin\mvn

I was thinking about this path, and how it might be wrong. I think that you need it to run bin\mvn.cmd instead of bin\mvn. That's probably where it's going wrong because bin\mvn is for Unix, and bin\mvn.cmd is for Windows.

You should be able to change tasks.json to tell it to use mvn.cmd instead.

**Comment by mat100payette** [comment]
That's exactly it. This issue also mentions that:
https://github.com/microsoft/vscode/issues/104343

I'll add a windows config to tasks.json.

**Comment by mat100payette** [comment]
I get the Extension Host to open with the first task, but no success with launching the java debug. Trying to launch it from the Extension Host or outside of it I always get the same Connection Refused error popup.

**Comment by joshtynjala** [comment]
> Trying to launch it from the Extension Host or outside of it I always get the same Connection Refused error popup.

You need to start both "Launch Extension" and "Debug SWF Debug Adapter (Attach)" from your main VSCode window. Then, inside the Extension Host window, launch a SWF debug session.

**Comment by joshtynjala** [comment]
Potentially, you might need to start with "Launch Extension" in the main window. Then, start a SWF debug session in the Extension Host window. Then, run "Debug SWF Debug Adapter (Attach)" back in the main window.

**Comment by mat100payette** [comment]
It's so weird... most places where I try to inspect `const` they dont show up.

For example I have this function:
```as
public function stringify():String
{
    const preStringified:String = JSON.stringify(this, replacer(this));
    var json:Object = JSON.parse(preStringified);

    for (var key:String in _compatSettings)
        json[key] = _compatSettings[key];

    var stringified:String = JSON.stringify(json);

    return stringified;
}
```

It decompiles to the following:
```as
public function stringify() : String
{
    var _loc1_:String = JSON.stringify(this,replacer(this));
    var json:Object = JSON.parse(_loc1_);
    for(var key in _compatSettings)
    {
    json[key] = _compatSettings[key];
    }
    return JSON.stringify(json);
}
```
However (!) if I change the declaration of `preStringify` to use `var` instead of `const`, it then decompiles to this:
```as
public function stringify() : String
{
    var preStringified:String = JSON.stringify(this,replacer(this));
    var json:Object = JSON.parse(preStringified);
    for(var key in _compatSettings)
    {
    json[key] = _compatSettings[key];
    }
    return JSON.stringify(json);
}
```

We can also see in the lower level instructions that with `const`, the local is never pushed:
```
debug 1, "json", 1, 0
debug 1, "stringified", 2, 0
debug 1, "key", 3, 0
```
but with `var`, it is...
```
debug 1, "preStringified", 0, 0
debug 1, "json", 1, 0
debug 1, "stringified", 2, 0
debug 1, "key", 3, 0
```

I'm guessing this is out of the scope of this repo ?

**Comment by joshtynjala** [comment]
Yeah, if you're seeing differences in bytecode between `var` and `const`, it's your AS3 compiler that is generating the bytecode.

It may be that Adobe may have considered the possibility of future new features, such as inlined constants, so they didn't want to expose them in the debugger when they might eventually disappear.

**Comment by mat100payette** [comment]
Although the `const` isn't given a debug name, would it still be possible to display them?

For example, in this case, the const `preStringified` essentially becomes `local1`, used in the op codes like so:
```
debugline 128
callproperty QName(PackageNamespace(""),"replacer"), 1
callproperty QName(PackageNamespace(""),"stringify"), 2
coerce_s
setlocal1
getlex QName(PackageNamespace(""),"JSON")
getlocal1
```
where `debugline 128` is this:
```as
const preStringified:String = JSON.stringify(this, replacer(this));
```

**Comment by mat100payette** [comment]
I can see that for that `const`, the code path is different than that of the named locals. At line 2245 of the `DManager.class` file of the flash debugger, the flag `inScopeChain` evaluates to `true` for the local named `"1"`, which is essentially that `local1` unnamed `const`. Therefore, it calls this:
```as
context.addScopeChainEntry(v);
```
instead of this:
```as
context.addLocal(v);
```

**Comment by joshtynjala** [comment]
> Although the const isn't given a debug name by the compiler, would it still be possible to display them?

If Adobe's Flash debugger exposes a way to access local1 and other unnamed constants, then yes, it would be possible to display them. As I said, though, I could not find an API where those are exposed.

> Therefore, it calls this: `context.addScopeChainEntry(v);` instead of this: `context.addLocal(v);`

However, with the name `addScopeChainEntry` in mind, I see that the `flash.tools.debugger.Frame` type has a `getScopeChain()` method, and I am not currently using it in the debug adapter (mainly, because I didn't know it's purpose). This could be where constants without debug names can be accessed.

Based on the documentation for `getScopeChain()`, I suspect that it may contain other data that isn't necessarily relevant for displaying in the GUI, so it might need some kind of filtering rather than displaying everything that gets returned.

**Comment by mat100payette** [comment]
Yes, if I breakpoint at line 1743 that you mentioned earlier, I can find/inspect that unnamed constant under:
`swfFrame > fFrame > m_scopeChain > 1` (or by calling `swfFrame.getScopeChain(swfSession)[1]`).

**Comment by joshtynjala** [comment]
Interestingly, if I compile with Apache Flex 4.16.1, I can see the local `const` values in the debugger with `getLocals()`. If I compile with AIR SDK & Compiler 33.1.1.633, I do not see local `const` values in the debugger.

However, with AIR SDK & Compiler 33.1.1.633, I also can't seem to find local `const` values when calling `swfFrame.getScopeChain()` either. I don't know if I'm trying to use the wrong `Frame`, or if it's something else. It's strange that you can see them when I cannot.

Which SDK are you using to compile?

**Comment by joshtynjala** [comment]
This is the code that I tested with, by the way:

```as3
public function testMethod():void
{
	const hi:String = "<<<hi>>>";
	const num:Number = 123.4;
	const hello:Object = {hello: "world"};
	
	trace("AT BREAKPOINT"); //add breakpoint here
}
```

**Comment by mat100payette** [comment]
Hmmm, interesting. I'm using AIR SDK and compiler v32.0.0.116. Also, just wanna repeat that I do see _some_ constants, but it looks like in some cases the compiler simply removes the debug name if it deems it is not needed. I don't know what exact cases cause it, nor do I have a minimal example at the moment, sorry.

**Comment by mat100payette** [comment]
Here's the link to the exact version we use:
http://airdownload.adobe.com/air/win/download/32.0/AIRSDK_Compiler.zip

**Comment by mat100payette** [comment]
I can reproduce the same issue with AIR SDK v33.1.1.713.

**Comment by mat100payette** [comment]
As for this:
> However, with AIR SDK & Compiler 33.1.1.633, I also can't seem to find local const values when calling swfFrame.getScopeChain() either. I don't know if I'm trying to use the wrong Frame, or if it's something else. It's strange that you can see them when I cannot.

I can't help right now. What you can do though is decompile the code you're debugging and check the low level code to figure out what `localX` your consts are mapped to. In my code above, here's the full low level code it produces:

```
trait method QName(PackageNamespace(""),"stringify")
   flag METADATA
   metadata"__go_to_definition_help"
      item "pos" "5336"
   end ; metadata
   dispid 0
   method
      name "stringify"
      returns QName(PackageNamespace(""),"String")
      
      body
         maxstack 4
         localcount 7
         initscopedepth 0
         maxscopedepth 1
         
         code
            getlocal0
            pushscope
            debugfile "c:\\Users\\matpa\\OneDrive\\Documents\\rCubed\\src;classes;UserSettings.as"
            debug 1, "json", 1, 0
            debug 1, "stringified", 2, 0
            debug 1, "key", 3, 0
            getlex QName(PackageNamespace(""),"JSON")
            getlocal0
            findpropstrict QName(PackageNamespace(""),"replacer")
            getlocal0
            debugline 128
            callproperty QName(PackageNamespace(""),"replacer"), 1
            callproperty QName(PackageNamespace(""),"stringify"), 2
            coerce_s
            setlocal1
            getlex QName(PackageNamespace(""),"JSON")
            getlocal1
            debugline 129
            callproperty QName(PackageNamespace(""),"parse"), 1
            coerce QName(PackageNamespace(""),"Object")
            setlocal2
            pushbyte 0
            setlocal 6
            getlex QName(PrivateNamespace("classes:UserSettings"),"_compatSettings")
            setlocal 5
            jump ofs0061
   ofs0047:
            label
            getlocal 5
            getlocal 6
            nextname
            coerce_s
            setlocal 4
            getlocal2
            getlocal 4
            getlex QName(PrivateNamespace("classes:UserSettings"),"_compatSettings")
            getlocal 4
            debugline 132
            getproperty MultinameL([PrivateNamespace("classes:UserSettings"),ProtectedNamespace("classes:UserSettings"),StaticProtectedNs("classes:UserSettings"),StaticProtectedNs("Object"),PackageNamespace("classes"),PackageInternalNs("classes"),PrivateNamespace("FilePrivateNS:UserSettings"),PackageNamespace(""),Namespace("http://adobe.com/AS3/2006/builtin")])
            setproperty MultinameL([PrivateNamespace("classes:UserSettings"),ProtectedNamespace("classes:UserSettings"),StaticProtectedNs("classes:UserSettings"),StaticProtectedNs("Object"),PackageNamespace("classes"),PackageInternalNs("classes"),PrivateNamespace("FilePrivateNS:UserSettings"),PackageNamespace(""),Namespace("http://adobe.com/AS3/2006/builtin")])
   ofs0061:
            hasnext2 5, 6
            iftrue ofs0047
            getlex QName(PackageNamespace(""),"JSON")
            getlocal2
            debugline 134
            callproperty QName(PackageNamespace(""),"stringify"), 1
            coerce_s
            setlocal3
            getlocal3
            debugline 136
            returnvalue
         end ; code
      end ; body
   end ; method
end ; trait
```

**Comment by mat100payette** [comment]
My guess would be that since you dont do anything with the constant variables, the compiler might fully get rid of them, hence why you wouldn't see them even in the scope chain.

**Comment by mat100payette** [comment]
What code is triggered when you hover over a member?

**Comment by mat100payette** [comment]
I know this is farfetched, but please hear me out.

When decompiled, as shown above, we can clearly see that the `debugline X` displays the proper line in the source code where the assignment was done. So imagine the following process:

1. The extension stores (at session start) a decompiled version of the SWF.
2. A variable lookup is requested.
3. The variable is not found, and the code is about to throw a new `NoSuchVariableException(o);`.
4. Before throwing, the extension looks up the following information:
    i. the decompiled data for the appropriate file;
    ii. the assembly snippet for the appropriate enclosing method.
5. Then, for each scope chain variable (indexed with index N for example), in order, do the following:
    i. locate the `setlocalN` instruction;
    ii. navigate upwards in the instructions until a `debugline X` is found;
    iii. parse the source file at line X, then:
    ....a. if in the format `const ___ =`, extract the const's name and check if it matches the initial request's argument
    ........- if it matches, return the scope chain variable at index N
    ........- if it doesn't match, throw the `NoSuchVariableException(o);` as normal
    ....b. if not in the format `const ___ =`, throw the `NoSuchVariableException(o);` as normal.

**Comment by mat100payette** [comment]
@joshtynjala Mind helping me out adding this jar dependency ? It's not on maven central, and I legit have no experience with maven/pom.xml stuff
[ffdec_lib_15.0.0.zip](https://github.com/BowlerHatLLC/vscode-swf-debug/files/7823425/ffdec_lib_15.0.0.zip)
.

**Comment by joshtynjala** [comment]
> My guess would be that since you dont do anything with the constant variables, the compiler might fully get rid of them, hence why you wouldn't see them even in the scope chain.

Even if I do something with them, it's the same.

> Mind helping me out adding this jar dependency ? It's not on maven central, and I legit have no experience with maven/pom.xml stuff

I don't a ton of experience with Maven. I remember seeing that there's a way to reference local .jar files in the pom.xml file, but I have never needed to do it, so I would need to look it up too.

**Comment by mat100payette** [comment]
> Even if I do something with them, it's the same.

I'd blame the compiler for doing cryptic stuff lol...

> I don't a ton of experience with Maven. I remember seeing that there's a way to reference local .jar files in the pom.xml file, but I have never needed to do it, so I would need to look it up too.

If you ever get some time to attempt it, it would be fantastic. Once I'm up and running with that dependency, I can probably manage most of the code myself.

**Comment by joshtynjala** [comment]
> If you ever get some time to attempt it, it would be fantastic.

I don't see myself having time. Feel free to try it yourself.

**Comment by mat100payette** [comment]
@joshtynjala Just to keep you updated, turns out `scopeChain` has nothing to do with this. I have managed to do the plan I described, but now really the only thing I'm missing is Where on earth are these `_loc1_` values stored ? I can't help but assume they must be somewhere for the debugger to query, regardless how cryptic their location may be. No ?

**Comment by joshtynjala** [comment]
> I can't help but assume they must be somewhere for the debugger to query, regardless how cryptic their location may be. No ?

Yes, I would think that they'd be available somewhere, even if there isn't a public API to get them. I just don't know where. Nor where to start looking.

**Comment by joshtynjala** [comment]
It's unlikely that anything is missing in the Royale debugger. However, if you want, you can compare to the debugger in the Apache Flex SDK, which is also open source and should have the exact same Java API. I don't think that the AIR SDK & Compiler's debugger would have diverged much at all from those two.

**Comment by mat100payette** [comment]
From the [AVM2 specs](https://www.adobe.com/content/dam/acom/en/devnet/pdf/avm2overview.pdf) (emphasis is mine)
_Logging my thoughts and findings here for better documentation._

**Pages 7-8:**

> The local data area for the method consists of the operand stack, the scope stack, and the local registers.
>
> o The operand stack holds operands for the instructions and receives their results.  Arguments 
> are pushed onto the stack top or popped off the stack top.  The top element always has 
> address 0; the one below it has address 1, and so on.  Stack addresses are not used except as a 
> specification mechanism. 
>
> o The scope stack is part of the run-time environment and holds objects that are to be searched 
> by the AVM2 when an instruction is executed that calls for name lookup.  Instructions push 
> elements onto the scope stack as part of the implementation of exception handling, closure 
> creation, and for the ActionScript 3.0 with statement. 
>
> o The local registers hold parameter values, local variables **in some cases**, and **temporaries**.

I wonder what these cases are, and what exactly is a "temporary".

**Page 13:**

> Unlike many traditional execution environments the debugging facilities of the AVM2 are tightly intertwined 
> with a series of instructions that are placed directly in the execution stream. To track current file name and line 
> number information debugfile and debugline are **emitted at appropriate points** in the instruction stream. In 
> cases where additional debugging detail is required, the debug instruction is used. For example, the names of 
> local variables are provided by this mechanism.

Would be good to know what exactly is an "appropriate point" to insert debug instructions.

**Page 15:**

> When control enters a method, three local data areas are allocated for it, as outlined in Chapter 2—an operand 
> stack segment, a scope stack segment, and a set of local registers.  The operand stack segment holds operands to 
> the instructions; values are pushed onto that stack or popped off it by most instructions.  The scope stack 
> segments holds scope objects in which the virtual machine will look up names at execution time.  Objects are 
> pushed onto the scope stack by OP_pushscope and OP_pushwith, and popped off by OP_popscope and by the 
> exception handling machinery.  The local registers hold parameter values, local variables, and temporaries.
> 
> On method entry, the state of these data areas is as follows. 
> • The operand stack is empty and has room for method_body_info.max_stack values. 
> • **The scope stack is empty and has room for method_body_info.max_scope_stack values**. 
> • **There are method_body_info.local_count registers**. 
> • Register 0 holds the “this” object.  This value is never null. 
> • Registers 1 through method_info.param_count holds parameter values coerced to the declared types 
> of the parameters.  If fewer than method_body_info.local_count values are supplied to the call then 
> the remaining values are either the values provided by default value declarations (optional arguments) 
> or the value undefined. 
> • If NEED_REST is set in method_info.flags, the method_info.param_count+1 register is set up to 
> reference an array that holds the superflous arguments. 
> • If NEED_ARGUMENTS is set in method_info.flags, the method_info.param_count+1 register is set up 
> to reference an “arguments” object that holds all the actual arguments: see ECMA-262 for more 
> information.  (The AVM2 is not strictly compatible with ECMA-262; it creates an Array object for 
> the “arguments” object, whereas ECMA-262 requires a plain Object.)

Decompiled code shows that:
1. `method_body_info.max_scope_stack` never counts the `const` unnamed variables.
2. `method_body_info.local_count` does count them.

**Page 19:**

> The constant_pool is a variable length structure composed of integers, doubles, strings, namespaces, 
namespace sets, and multinames.  These constants are **referenced from other parts** of the abcFile 
structure.  

Not entirely sure what these parts are yet.

**Page 33:**

> The local_count field is the index of the highest-numbered local register this method will use, plus one.

**Pages 52-53:**

> debug_type is an unsigned byte. If the value of debug_type is DI_LOCAL (1), then this is 
> debugging information for a local register.  
> index is a u30 that must be an index into the string constant pool. The string at index is the 
> name to use for this register.  
> 
> reg is an unsigned byte and is the index of the register that this is debugging information for.  
> 
> extra is a u30 that is currently unused.  
>
> When debug_type has a value of 1, **this tells the debugger the name to display for the register 
> specified by reg**. If the debugger is not running, then this instruction does nothing.

Given the statement in emphasis, and the fact that named variables generate an instruction in the form:
```
debug 1, "x", 10, 0
```
you would think that the debugger has a way to request a value from any specific local register, _especially_ since variable names cannot consist of just a single digit (i.e. `var 1:int = 0;` is illegal). That being said, if the debugger forms such a local register request, it _should_ be able to not use the local debug name and just use the register's index.

**Comment by mat100payette** [comment]
This variable looks so suspicious imo:
https://github.com/apache/royale-compiler/blob/eeebcdb619bf07f850f1ae56f8b8744e205e1cca/debugger/src/main/java/flash/tools/debugger/concrete/DManager.java#L1487

It looks awfully like what should be an array of the frame's local registers. However, the call `int num = (int) msg.getDWord();` always seem to give me `0` when stopping on a breakpoint in the method. Strange.

**Comment by mat100payette** [comment]
What exactly creates/sends these messages that the `DManager` parses? If `registers` is always 0, chances are the messages just dont include the necessary data for the debugger to query their content.

**Comment by joshtynjala** [comment]
It looks like DMessage objects are created by DProtocol. The content of a DMessage is parsed from data received over a socket connection with Flash Player or AIR.

**Comment by mat100payette** [comment]
@joshtynjala I opened a discussion in the air sdk main github. Letting you know in case you're interested:
https://github.com/airsdk/Adobe-Runtime-Support/discussions/1541

**Comment by mat100payette** [comment]
@joshtynjala Can you confirm that with air sdk 33.1.1.758 (or higher) you can inspect all `const` now ? My discussion with HARMAN ended and they've added it to the runtime. Thanks for all your help too.

**Comment by joshtynjala** [comment]
Confirmed that I see local constants in the debugger when using AIR 33.1.1.795.
