### ISSUE TITLE
Unable to access non-local, non-public members from breakpoint inside function closure

### ISSUE THREAD

**Issue by esidegallery** [BowlerHatLLC/vscode-swf-debug#40]
Confirmed in a fresh installation of the latest VSCode with the ActionScript & MXML extension on Windows 10 x64.

When debugging a breakpoint inside a function closure, private and protected vars and consts are evaluating as 'undefined', even though they are programmatically within the closure's scope

![MXML Function Closures](https://user-images.githubusercontent.com/354051/179521189-d013e7df-976e-4e9b-9bf5-c74ee20f82cd.gif)

**Comment by joshtynjala** [comment]
I barely figured out how to get watch/evaluate to work at all in the current local scope. It's probably unlikely that I'll figure out how to evaluate a variable from another scope. Not that I wouldn't want to. Just trying to set expectations.

**Comment by joshtynjala** [comment]
Just leaving myself a note. Adding this somewhere in `SWFExpressionContext.lookup()` seems to get variables from the scope chain (such as outer scopes of a closure):

```java
Variable[] scopes = contextFrame.getScopeChain(swfSession);
for (Variable scope : scopes) {
	Variable[] members = scope.getValue().getMembers(swfSession);
	if (members != null) {
		for (Variable member : members) {
			if (member.getName().equals(memberName)) {
				return member;
			}
		}
	}
}
```

I'm not yet sure exactly where it should be placed. It may be that `this` needs to be checked first in some cases. Needs further testing.
