### ISSUE TITLE
Cannot edit Number variable with a value of two or more decimals in the fractional part

### ISSUE THREAD

**Issue by Adolio** [BowlerHatLLC/vscode-swf-debug#45]
Hi Josh,

While tweaking a variable via the debugger (when stopped at a breakpoint), I noticed that entering a number value with two or more decimals in the fractional part generates an error:

OK when typing `0.8`
![Ok 0 8](https://user-images.githubusercontent.com/1126990/233741552-7ff714d5-6622-4806-af8b-d980b50e2666.png)

Error when typing `0.85`
![Error 0 85](https://user-images.githubusercontent.com/1126990/233741550-c57b5ebe-b17b-483e-9d62-e921c7fe177e.png)

Best,
Aurélien

**Comment by joshtynjala** [comment]
c14be0df941a441b155f72123901b6d0a0fa770f

**Comment by Adolio** [comment]
Thanks @joshtynjala for the fix 👌
