### ISSUE TITLE
Where should I set the debug player's path?  

### ISSUE THREAD

**Issue by VishwasGagrani** [BowlerHatLLC/vscode-swf-debug#49]
To make it work I have to set "open all swf with debug player" because by default it always launches the release-player. 
So how can I change this path in the vscode extension 
C:\Program Files\Adobe\Adobe Animate 2024\Players\FlashPlayer.exe 
To this path : 
C:\Program Files\Adobe\Adobe Animate 2024\Players\Debug\FlashPlayerDebugger.exe

I also tried to use "runtimeExecutable" in launch.json  to set flash debug player.  But it does not allow that attribute it in the first place.

**Comment by joshtynjala** [comment]
`runtimeExecutable` in _launch.json_ is indeed the correct way to provide a custom Flash Player executable.

I just confirmed that it works. Here it is with a macOS path, but it would be similar for a Windows exe.

```jsonc
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"type": "swf",
			"request": "launch",
			"name": "Launch SWF",
			"runtimeExecutable": "/Applications/Flash Player.app/Contents/MacOS/Flash Player Debugger"
		}
	]
}
```
