### ISSUE TITLE
Debugger breakpoints does not work inside fx:Script inside fx:Component

### ISSUE THREAD

**Issue by AndreaFilippi** [BowlerHatLLC/vscode-swf-debug#51]
Hello,
The debugger is not allowing me to stop inside the fx:Script code, if I try to set a breakpoint it becames gray and ignored.
I want to understand if this is a wanted behavior or a bug given that in the same place if an exception occurs the debugger is able to correctly stop there and show also the Locals variables.

Please find attached:

1.The code showing a gray breakpoint and the debugger able to stop on an exception in the same function. 
![1](https://github.com/BowlerHatLLC/vscode-as3mxml/assets/13135708/8a5356ce-d851-48f7-81a0-a8bc382b34b9)

2.A complete picture of the mxml class structure. 
![2](https://github.com/BowlerHatLLC/vscode-as3mxml/assets/13135708/184b0a79-8353-427f-9af4-134e5942fe1f)

3.The .ascode compiler settings.
![3](https://github.com/BowlerHatLLC/vscode-as3mxml/assets/13135708/c91cdf0c-8eb6-4463-a45c-070e1cfa34b2)

Environment:
ActionScript & MXML v1.21.1
AIR51.0
FLEX 4.16.1

**Comment by joshtynjala** [comment]
Hmmm... In the following .mxml file, I can add successfully add breakpoints to both of the lines with `trace()` calls.

```mxml
<?xml version="1.0" encoding="utf-8"?>
<s:WindowedApplication xmlns:fx="http://ns.adobe.com/mxml/2009"
	xmlns:s="library://ns.adobe.com/flex/spark"
	xmlns:mx="library://ns.adobe.com/flex/mx"
	applicationComplete="onAppComplete()">

	<mx:Button label="Click Me" click="onButtonClick(event)"/>

	<fx:Script>
		<![CDATA[
			import flash.events.MouseEvent;

			private function onAppComplete():void
			{
				trace("app complete");
			}
			
			private function onButtonClick(event:MouseEvent):void
			{
				trace("clicked");
			}
		]]>
	</fx:Script>
</s:WindowedApplication>
```

I wonder if it's because your `<fx:Script>` is inside an `<mx:Component>` tag. Perhaps the debugger isn't handling that correctly.

**Comment by joshtynjala** [comment]
I can reproduce with the following file, and it does indeed seem to require `<fx:Script>` inside `<fx:Component>`. Adding the breakpoint on the `trace()` line shows debug console output, but does not stop on the breakpoint or show it as verified.

```mxml
<?xml version="1.0" encoding="utf-8"?>
<s:WindowedApplication xmlns:fx="http://ns.adobe.com/mxml/2009"
	xmlns:s="library://ns.adobe.com/flex/spark"
	xmlns:mx="library://ns.adobe.com/flex/mx">
	<s:layout>
		<s:VerticalLayout gap="10" padding="10"/>
	</s:layout>
	<s:List labelField="text" width="100%" height="100%">
		<s:itemRenderer>
			<fx:Component>
				<s:ItemRenderer click="onClick(event)">
					<s:Label text="{data.text}"/>
					<fx:Script>
					<![CDATA[
						import flash.events.MouseEvent;

						private function onClick(event:MouseEvent):void
						{
							trace("click");
						}
					]]>
					</fx:Script>
				</s:ItemRenderer>
			</fx:Component>
		</s:itemRenderer>
		<s:dataProvider>
			<s:ArrayList>
				<fx:Object text="One"/>
				<fx:Object text="Two"/>
				<fx:Object text="Three"/>
			</s:ArrayList>
		</s:dataProvider>
	</s:List>
</s:WindowedApplication>
```
