### ISSUE TITLE
BreakPoints get error

### ISSUE THREAD

**Issue by tidus2020** [BowlerHatLLC/vscode-swf-debug#8]
> error while processing request '{_request}'{_exception}

When debugger and add a breakPoint, I will get this error , the breakPoint is not working.

**Comment by joshtynjala** [comment]
I was able to reproduce this issue. I'll include the fix in the next update (I don't know when that will be yet).

**Comment by joshtynjala** [comment]
@tidus2020 I just released vscode-swf-debug v1.1.2, which includes the fix mentioned in my previous comment. Please update and let me know if it helps or not.
